## pandas-funcs-2

In [ ]:
import pandas as pd

In [ ]:
# 샘플 데이터 - 1990년 California 주택 데이터
csv_file_url = "https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"
df = pd.read_csv(csv_file_url, sep=",")

In [ ]:
# drop
len(df), len(df.columns)

(17000, 9)

In [ ]:
df_rows_dropped = df.drop(df.index[0:10000])
len(df_rows_dropped)

7000

In [ ]:
df_cols_dropped = df.drop(["population", "households"], axis=1)
len(df_cols_dropped.columns)

7

In [ ]:
# sort_values
df_sorted = df.sort_values(by="population")
df_sorted

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8232,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.5360,350000.0
2990,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.3750,137500.0
14105,-122.06,37.39,26.0,18.0,4.0,8.0,4.0,3.7500,375000.0
2907,-117.76,35.22,4.0,18.0,3.0,8.0,6.0,1.6250,275000.0
288,-116.76,34.14,4.0,42.0,10.0,9.0,3.0,0.5360,42500.0
...,...,...,...,...,...,...,...,...,...
3296,-117.87,34.04,7.0,27700.0,4179.0,15037.0,4072.0,6.6288,339700.0
2969,-117.78,34.03,8.0,32054.0,5290.0,15507.0,5050.0,6.0191,253900.0
2871,-117.74,33.89,4.0,37937.0,5471.0,16122.0,5189.0,7.4947,366300.0
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0
2274,-117.42,33.35,14.0,25135.0,4819.0,35682.0,4769.0,2.5729,134400.0

In [ ]:
# statistics functions
df["households"].sum()

np.float64(8520773.0)

In [ ]:
df["households"].max()

6082.0

In [ ]:
df["households"].min()

1.0

In [ ]:
df["households"].mean()

np.float64(501.2219411764706)

In [ ]:
df["households"].median()

409.0

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# 퀴즈
# california 데이터셋에서 median_income이 2.0 이상인 지역의 평균 median_house_value을 출력
df.loc[df["median_income"] >= 2.0, "median_house_value"].mean()

np.float64(220129.62980993665)

## pandas-funcs-3

In [ ]:
import pandas as pd

In [ ]:
# 샘플 데이터 - 1990년 California 주택 데이터
csv_file_url = "https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"
df = pd.read_csv(csv_file_url, sep=",")

In [ ]:
# 사칙연산
df["non_bedrooms"] = df["total_rooms"] - df["total_bedrooms"]
df["rooms_per_households"] = df["total_rooms"] / df["households"]

df.loc[:, ["non_bedrooms", "rooms_per_households"]]

       non_bedrooms  rooms_per_households
0            4329.0             11.889831
1            5749.0             16.522678
2             546.0              6.153846
3            1164.0              6.641593
4            1128.0              5.549618
...             ...                   ...
16995        1823.0              6.008130
16996        1821.0              5.051613
16997        2146.0              5.870614
16998        2120.0              5.589958
16999        1520.0              6.740741

[17000 rows x 2 columns]

In [ ]:
# isna
df_with_na = pd.DataFrame({"A": [None, 1], "B": [2, None]})
df_with_na.isna()

       A      B
0   True  False
1  False   True

In [ ]:
# fillna
df_with_na.fillna(0)

     A    B
0  0.0  2.0
1  1.0  0.0

In [ ]:
# isin
df["housing_median_age"].isin([3.0, 4.0]).sum()

np.int64(207)

## numpy-intro

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.__version__

'2.0.2'

In [ ]:
# ndarray
arr = np.array([2, 3, 1, 5, 4])
arr

array([2, 3, 1, 5, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# multi-dimension array
multi_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])
multi_dim_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(f"Dimensions: {multi_dim_arr.ndim}")
print(f"Shape: {multi_dim_arr.shape}")

Dimensions: 2
Shape: (2, 3)

In [ ]:
# Series로부터 ndarray가져오기
s = pd.Series([2, 3, 1, 5, 4])
s.values

array([2, 3, 1, 5, 4])

In [ ]:
type(s.values)

numpy.ndarray

In [ ]:
# indexing
arr = np.array([[2, 3, 4], [5, 6, 7]])
print(f"arr[0, 0] = {arr[0, 0]}")
print(f"arr[1, 2] = {arr[1, 2]}")
print(f"arr[-1, 2] = {arr[-1, 2]}")

arr[0, 0] = 2
arr[1, 2] = 7
arr[-1, 2] = 7

In [ ]:
arr_2 = np.array([3, 1, 2, 5, 7, 9, 10])
mask = arr_2 > 5
arr_2[mask]

array([ 7,  9, 10])

In [ ]:
# slicing
arr = np.array([[2, 3, 4], [5, 6, 7]])
print(f"arr[0, :] = {arr[0, :]}")
print(f"arr[0, 1:] = {arr[0, 1:]}")
print(f"arr[:1, 1] = {arr[:1, 1]}")

arr[0, :] = [2 3 4]
arr[0, 1:] = [3 4]
arr[:1, 1] = [3]

## numpy-func

In [ ]:
import numpy as np

In [ ]:
# arange
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [ ]:
# zeros
arr = np.zeros((2, 2))
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
# full
arr = np.full((2, 2), 1)
arr

array([[1, 1],
       [1, 1]])

In [ ]:
# eye
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

In [ ]:
# binary operations
arr_1 = np.array([[2, 3], [1, 4]])
arr_2 = np.array([[-1, 2], [4, 3]])

In [ ]:
np.add(arr_1, arr_2)

array([[1, 5],
       [5, 7]])

In [ ]:
np.subtract(arr_1, arr_2)

array([[ 3,  1],
       [-3,  1]])

In [ ]:
np.matmul(arr_1, arr_2)

array([[10, 13],
       [15, 14]])

In [ ]:
# 통계 함수들
arr = np.array([[2, 3, 7], [1, 4, 5]])
print(f"arr.max() = {arr.max()}")
print(f"arr.max(axis=0) = {arr.max(axis=0)}")
print(f"arr.max(axis=1) = {arr.max(axis=1)}")
print(f"arr.argmax(axis=1) = {arr.argmax(axis=1)}")

arr.max() = 7
arr.max(axis=0) = [2 4 7]
arr.max(axis=1) = [7 5]
arr.argmax(axis=1) = [2 2]

In [ ]:
print(f"arr.min(axis=0) = {arr.min(axis=0)}")
print(f"arr.argmin(axis=0) = {arr.argmin(axis=0)}")

arr.min(axis=0) = [1 3 5]
arr.argmin(axis=0) = [1 0 1]

In [ ]:
print(f"arr.sum() = {arr.sum()}")
print(f"arr.sum(axis=0) = {arr.sum(axis=0)}")
print(f"arr.mean(axis=1) = {arr.mean(axis=1)}")

arr.sum() = 22
arr.sum(axis=0) = [ 3  7 12]
arr.mean(axis=1) = [4.         3.33333333]

In [ ]:
# Shaping operations
arr = np.array([[2, 3, 1], [1, 2, -1]])
arr.shape

(2, 3)

In [ ]:
arr_reshaped = arr.reshape((3, 2))
arr_reshaped

array([[ 2,  3],
       [ 1,  1],
       [ 2, -1]])

In [ ]:
arr_flattened = arr.flatten()
arr_flattened

array([ 2,  3,  1,  1,  2, -1])

In [ ]:
arr_transposed = arr.transpose()
arr_transposed

array([[ 2,  1],
       [ 3,  2],
       [ 1, -1]])

In [ ]:
# Numerical operations
arr = np.array([2.2, 3.0, 1.3, 4.2])

print(f"np.exp(arr) = {np.exp(arr)}")
print(f"np.log(arr) = {np.log(arr)}")
print(f"np.log2(arr) = {np.log2(arr)}")
print(f"np.sqrt(arr) = {np.sqrt(arr)}")
print(f"np.power(arr, 3) = {np.power(arr, 3)}")
print(f"np.ceil(arr) = {np.ceil(arr)}")
print(f"np.floor(arr) = {np.floor(arr)}")

np.exp(arr) = [ 9.0250135  20.08553692  3.66929667 66.68633104]
np.log(arr) = [0.78845736 1.09861229 0.26236426 1.43508453]
np.log2(arr) = [1.13750352 1.5849625  0.37851162 2.07038933]
np.sqrt(arr) = [1.4832397  1.73205081 1.14017543 2.04939015]
np.power(arr, 3) = [10.648 27.     2.197 74.088]
np.ceil(arr) = [3. 3. 2. 5.]
np.floor(arr) = [2. 3. 1. 4.]